# Q1. 주어진 리스트에서 홀수만 남기고 짝수는 제거하여 출력하기

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# 리스트 내포를 사용하여 짝수를 걸러내기
odd_numbers = [num for num in numbers if num % 2 != 0]

# 결과 출력
print(odd_numbers)

[1, 3, 5, 7, 9]

# Q2. 주어진 딕셔너리에서 "age" 키의 값을 6으로 수정하여 전체 딕셔너리 출력하기

In [ ]:
person = {"name": "짱구", "age": 5, "city": "서울"}

# "age" 키의 값을 6으로 수정
person["age"] = 6

# 전체 딕셔너리 출력
print(person)

{'name': '짱구', 'age': 6, 'city': '서울'}

# Q3. 주어진 문자열을 공백을 기준으로 분리하고 각 단어의 첫 글자만 대문자로 변환하여 출력하기

In [ ]:
test1 = "python is easy"

# 문자열을 공백을 기준으로 분리하고 각 단어의 첫 글자를 대문자로 변환
result = ' '.join(word.capitalize() for word in test1.split())

# 결과 출력
print(result)

Python Is Easy

# Q4. 주어진 리스트의 합, 최댓값, 최솟값을 출력하기

In [ ]:
numbers_list = [10, 2, 8, 5, 15]

# 리스트의 합계 계산 및 출력
sum_value = 0
for num in numbers_list:
    sum_value += num
print(f"Sum: {sum_value}")

# 리스트의 최댓값 계산 및 출력
max_value = numbers_list[0]
for num in numbers_list[1:]:
    if num > max_value:
        max_value = num
print(f"Maximum: {max_value}")

# 리스트의 최솟값 계산 및 출력
min_value = numbers_list[0]
for num in numbers_list[1:]:
    if num < min_value:
        min_value = num
print(f"Minimum: {min_value}")

numbers_list = [10, 2, 8, 5, 15]

# 리스트의 합계 계산 및 출력
sum_value = sum(numbers_list)
print(f"Sum: {sum_value}")

# 리스트의 최댓값 계산 및 출력
max_value = max(numbers_list)
print(f"Maximum: {max_value}")

# 리스트의 최솟값 계산 및 출력
min_value = min(numbers_list)
print(f"Minimum: {min_value}")

Sum: 40
Maximum: 15
Minimum: 2
Sum: 40
Maximum: 15
Minimum: 2

# Q5. 주어진 문자열에서 모든 공백을 제거하고 대문자로 변환하여 출력하기

In [ ]:
text2 = "   hello world   "
# 공백 제거 및 대문자로 변환
result = text2.replace(" ", "").upper()

# 결과 출력
print(result)

HELLOWORLD

# Q6. 주어진 문자열에서 특정 문자가 몇 번 등장하는지 횟수 출력하기

In [ ]:
text3 = "python programming is powerful and pythonic"
target_char = "p"

# 문자열에서 특정 문자가 나타나는 횟수 계산
count = text3.count(target_char)

# 결과 출력
print(f"주어진 문자열에서 문자열'{target_char}'는 {count} 번 등장합니다.")

# 문자열에서 특정 문자가 나타나는 횟수 계산
count = sum(1 for char in text3 if char == target_char)
# 결과 출력
print(f"주어진 문자열에서 문자열'{target_char}'는 {count} 번 등장합니다.")

주어진 문자열에서 문자열'p'는 4 번 등장합니다.
주어진 문자열에서 문자열'p'는 4 번 등장합니다.

# Q7. 주어진 문자열을 3번 만큼 반복하여 출력하기

In [ ]:
text4 = "abc"

# 방법1 곱셈 연산자를 사용하여 문자열을 3번 반복
result1 = text4 * 3

# 결과 출력
print(result1)

# 방법2 join 메서드를 사용하여 문자열을 3번 반복
result2 = ''.join([text4] * 3)

# 결과 출력
print(result2)


# 루프를 사용하여 문자열을 3번 반복
result3 = ''.join(text4 for _ in range(3))

# 결과 출력
print(result3)

abcabcabc
abcabcabc
abcabcabc

# Q8. 주어진 리스트의 문자열 요소들을 모두 결합하여 출력하기

In [ ]:
string_list = ["Hello", " ", "World", "!"]

# 리스트의 문자열 요소를 합쳐서 출력
result = ''.join(string_list)

# 결과 출력
print(result)

Hello World!

# Q9. 주어진 문자열에서 특정 문자를 다른 문자로 치환하기(a -> o로 치환)

In [ ]:
text5 = "banana"

# 문자열에서 특정 문자 교체 (a -> o)
result = text5.replace("a", "o")

# 결과 출력
print(result)

bonono

# Q10. 주어진 문자열에서 숫자만 추출하여 출력하기

In [ ]:
text6 = "abc123def456"

# 리스트 컴프리헨션을 사용하여 숫자 추출
numbers4 = [char for char in text6 if char.isdigit()]

# 추출된 숫자 출력
for number in numbers4:
    print(number)


 # 루프와 isdigit()을 사용하여 숫자 추출
numbers2 = ''.join(char if char.isdigit() else ' ' for char in text6).split()

# 추출된 숫자 출력
for number in numbers2:
    print(number)

1
2
3
4
5
6
123
456

# Q11. 사용자가 입력한 정수값을 리스트에 저장하고 최대값과 최소값, 합계를 반환하는 함수
# 함수명 : number_mix
# 매개변수 o, 리턴값 o
# 3개 숫자 입력받아서 리스트에 저장하도록하기

In [1]:
def number_mix():
    # 리스트 컴프리헨션을 사용하여 사용자로부터 세 개의 정수 입력 받기
    numbers = [int(input("첫 번째 숫자를 입력하세요: ")), int(input("두 번째 숫자를 입력하세요: ")), int(input("세 번째 숫자를 입력하세요: "))]
    return max(numbers), min(numbers), sum(numbers)

result = number_mix()
print("최댓값:", result[0])
print("최솟값:", result[1])
print("합계:", result[2])


def number_mix2():
    # For 루프를 사용하여 사용자로부터 세 개의 정수 입력 받기
    numbers = []
    for i in range(3):
        numbers.append(int(input(f"{i + 1}번째 숫자를 입력하세요: ")))
    return max(numbers), min(numbers), sum(numbers)

result = number_mix()
print("최댓값:", result[0])
print("최솟값:", result[1])
print("합계:", result[2])

def number_mix3():
    # 리스트 컴프리헨션과 루프를 사용하여 사용자로부터 세 개의 정수 입력 받기
    numbers = [int(input(f"{i + 1}번째 숫자를 입력하세요: ")) for i in range(3)]
    return max(numbers), min(numbers), sum(numbers)

result = number_mix()
print("최댓값:", result[0])
print("최솟값:", result[1])
print("합계:", result[2])


def number_mix4():
    # While 루프를 사용하여 사용자로부터 세 개의 정수 입력 받기
    numbers = []
    i = 0
    while i < 3:
        numbers.append(int(input(f"{i + 1}번째 숫자를 입력하세요: ")))
        i += 1
    return max(numbers), min(numbers), sum(numbers)

result = number_mix()
print("최댓값:", result[0])
print("최솟값:", result[1])
print("합계:", result[2])

def number_mix5():
    # map() 및 split()을 사용하여 사용자로부터 세 개의 정수 입력 받기
    numbers = list(map(int, input("띄어쓰기로 구분된 세 숫자를 입력하세요: ").split()))
    return max(numbers), min(numbers), sum(numbers)

result = number_mix()
print("최댓값:", result[0])
print("최솟값:", result[1])
print("합계:", result[2])

SyntaxError: unterminated triple-quoted string literal (detected at line 72) (<ipython-input-1-007e3ac21de4>, line 61)

In [2]:
def number_mix():
    '''입력한 정수값을 리스트에 저장하고 최대값과 최소값, 합계를 반환'''
    numbers = []
    for i in range(3):
        num = int(input(f"{i+1}번째 숫자입력 : "))
        numbers.append(num)

    #최대값, 최소값, 합계 계산
    max_num = max(numbers)
    min_num = min(numbers)
    total = sum(numbers)

    return max_num, min_num, total

In [ ]:
#매개변수o, 리턴값o 사용자 정의함수

def number_mix1(numbers):
    '''전달된 리스트의 최대값, 최소값, 합계를 반환'''
    return max(numbers), min(numbers), sum(numbers)

numbers = []
for i in range(3):
    num = int(input(f"{i+1}번째 숫자입력 : "))
    numbers.append(num)

min, max, total = number_mix1(numbers)
print(f"최소값 : {min}")
print("출력끝")

# Q12. 리스트 평균 계산
# 함수명 : list_avg
# 매개변수 o, 반환값 o
- 매개변수 : 숫자로 이루어진 리스트
- 반환값: 리스트의 평균을 반환

In [ ]:
def list_avg(numbers):
    # 리스트가 비어 있는지 확인하여 0으로 나누는 오류를 방지합니다.
    if len(numbers) == 0:
        return None  # 특정 값을 반환하거나 예외를 발생시키도록 필요에 따라 수정할 수 있습니다.

    # 평균을 계산합니다.
    average = sum(numbers) / len(numbers)

    return average

my_list = [1, 2, 3, 4, 5]
result = list_avg(my_list)
print(f"리스트 {my_list}의 평균은: {result}")

리스트 [1, 2, 3, 4, 5]의 평균은: 3.0

In [ ]:
print(not True)
li = [1]
print(bool(li))

In [ ]:
#1. 함수명 정의(numbers):
#2. 리스트의 합계 계산
#3. 평균계산
#4. 반환값

def list_avg(numbers):
    if not numbers:
        return 0

    total = sum(numbers)
    avg = total / len(numbers)
    return avg

li1 = [10, 20, 30, 40, 50]
result = list_avg(li1)
print(result)
li2 = []
result = list_avg(li2)
print(result)

# Q13. 코드해석 문제
- 아래 코드 주석달아서 모두 해석해보고 객체 생성 시 어떻게 동작하는지 순서 작성하기

In [ ]:
# Car 클래스 정의
class Car:
    # 자동차의 세부 정보(브랜드, 모델, 연도)를 설정하는 메서드
    def set_details(self, brand, model, year):
        self.brand = brand
        self.model = model
        self.year = year

    # 자동차 정보를 표시하는 메서드
    def display_info(self):
        print(f"브랜드: {self.brand}\n모델: {self.model}\n연도: {self.year}")

# Car 클래스의 인스턴스 생성 (car1)
car1 = Car()

# car1의 세부 정보 설정 (Toyota Camry, 2022)
car1.set_details("Toyota", "Camry", 2022)

# car1의 정보 표시
car1.display_info()

# 출력 가독성을 위해 빈 줄 추가
print()

# Car 클래스의 또 다른 인스턴스 생성 (car2)
car2 = Car()

# car2의 세부 정보 설정 (Honda Accord, 2021)
car2.set_details("Honda", "Accord", 2021)

# car2의 정보 표시
car2.display_info()


# 1 'car1'을 생성하고 세부정보를 설정합니다.
# 2. 'car1'에 대한 정보를 표시합니다.
# 3. 빈 줄을 인쇄합니다.
# 4. 'car2'를 생성하고 세부정보를 설정합니다.
# 5.'car2'에 대한 정보를 표시합니다.

Brand: Toyota
Model: Camry
Year: 2022

Brand: Honda
Model: Accord
Year: 2021